[package]
name = "guessing_game"
version = "0.2.1"
authors = ["Tom Watt <tom.watt@spongelearning.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
rand = "0.8.3"